receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: prometheus-spring-metrics
          static_configs:
            - targets: ['springmongodb:9464']

exporters:
  prometheus: # Expondo métricas no formato prometheus
    endpoint: "0.0.0.0:8989"

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
