receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318
        cors:
          allowed_origins:
            - http://*

processors: 
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  otlp:
    endpoint: otel-collector:4318
  elasticsearch: 
    endpoint: http://elasticsearch:9200

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [elasticsearch]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [elasticsearch]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [elasticsearch]      