spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/BookstoreDb'
      database: BookstoreDb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8080/realms/SpringBootRealm'
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
